### ISSUE TITLE
Hello Sir i need Dual Usb Camera App

### ISSUE THREAD

**Issue by heaveninfosoft** [shengjunhu/android_sample_uvccamera#1]
Can you Help me to Build Dual USB Camera  (Supporting HD ,FHD) Camera.
Recording , Image Capturing , Straming ...

**Comment by shengjunhu** [comment]
> Can you Help me to Build Dual USB Camera (Supporting HD ,FHD) Camera.
> Recording , Image Capturing , Straming ...

This library supports dual USB cameras. Whether it supports HD and frame rate depends on your USB bandwidth and Camera hardware. About recording and streaming is currently in the development and testing stage.

**Comment by heaveninfosoft** [comment]
@shengjunhu when will you complete??
i need complete code of Dual USB Camera (Supporting HD ,FHD) Camera.
Recording , Image Capturing , Straming ...

**Comment by shengjunhu** [comment]
> @shengjunhu when will you complete??
> i need complete code of Dual USB Camera (Supporting HD ,FHD) Camera.
> Recording , Image Capturing , Straming ...

At present, the work is relatively busy and the specific time cannot be determined.
