### ISSUE TITLE
能否支持264解码显示呢？

### ISSUE THREAD

**Issue by cwjfeifei** [shengjunhu/android_sample_uvccamera#4]

**Comment by shengjunhu** [comment]
现有的版本没有实现H264解码，UVC支持的原始格式就是YUYV和MJPEG，
如果你必须使用H264的话，推荐你在源码中libuvc中的frame.c中实现H264格式的解码即可
H264解码推荐使用FFmpeg 或 MediaCodec，解码速度决定预览效果

**Comment by cwjfeifei** [comment]
我现在用MediaCodec解码264，方式是将底层的数据回传到Java层，但是效率很低，我想在JNI层解析，但是不知道如何实现？大兄弟能否提供一下思路？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Shengjun&amp;nbsp;Hu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月25日(星期五) 下午4:53
收件人:&nbsp;&quot;shengjunhu/android_sample_uvccamera&quot;<android_sample_uvccamera@noreply.github.com&gt;;
抄送:&nbsp;&quot;feifei&quot;<603957521@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shengjunhu/android_sample_uvccamera] 能否支持264解码显示呢？ (#4)

**Comment by cwjfeifei** [comment]
我现在用MediaCodec解码264，方式是将底层的数据回传到Java层，但是效率很低，我想在JNI层解析，但是不知道如何实现？大兄弟能否提供一下思路？

**Comment by shengjunhu** [comment]
> 我现在用MediaCodec解码264，方式是将底层的数据回传到Java层，但是效率很低，我想在JNI层解析，但是不知道如何实现？大兄弟能否提供一下思路？

1-MediaCodec Java接口实现硬解码里面也是native，正常情况不会很低
2-如果Android版本兼容的情况下，你也可以使用NDK自带的MediaCodec
3-第三方解码库：x264、ffmpeg
如果那一步遇到问题的话，可以相互探讨一下
(正常UVC原始格式是YUYV or UYUV格式的，你那边拿到的原始数据格式就是H264吗？
还是说在哪个环节处理后生成的H264格式)

**Comment by cwjfeifei** [comment]
能否加个微信或者QQ呢？我的微信发你邮箱

**Comment by shengjunhu** [comment]
> 我现在用MediaCodec解码264，方式是将底层的数据回传到Java层，但是效率很低，我想在JNI层解析，但是不知道如何实现？大兄弟能否提供一下思路？

[UVC_H264](https://github.com/liuxuanhai/USB_Camera/tree/master/UVC_h264)
这个库里面包括了MJPG解码，H264的编解码
