### ISSUE TITLE
Very slow and wrong orientation

### ISSUE THREAD

**Issue by ToysoftInc** [shengjunhu/android_sample_uvccamera#5]
Thanks for the demo.  Some issues

Device: Samsung S9 OS10

1. Preview is very sluggish
2. Preview orientation is in landscape
3. How to take picture and record video?

**Comment by shengjunhu** [comment]
> Thanks for the demo. Some issues
> 
> Device: Samsung S9 OS10
> 
> 1. Preview is very sluggish
> 2. Preview orientation is in landscape
> 3. How to take picture and record video?

UVC Camera isn't suitable for large resolutions.
You can call UVCCamera#setPreviewRotate(90).
There is no recording video function yet.
